export default {
  Containers: [
    'Container components act as wrappers for displaying content or other components.',
    [
      'Card',
      'ChatWindow',
      'Collapse',
      'Drawer',
      'Jumbotron',
      'Modal',
      'Overlay',
    ],
  ],
  Content: [
    'Content components are used to control how content is formatted and displayed.',
    [
      'Accordion',
      'Avatar',
      'Badge',
      'Gallery',
      'Quotation',
      'Comment',
      'Post',
      'Tabs',
      'Tag',
      'Truncate',
      'UserPersona',
    ],
  ],
  'Data Display': [
    'Data display components are used to format and display data in an organized format.',
    ['CheckList', 'List', 'ListItem', 'Table'],
  ],
  DOM: [
    "DOM components are used to interact with elements on the page outside of the current component's scope.",
    ['Portal'],
  ],
  'Form Controls': [
    'Form Controls are simple UI elements such as buttons and form fields. They are interacted with by the user in order to trigger an action.',
    [
      'AutoComplete',
      'Button',
      'ButtonGroup',
      'CheckOption',
      'CheckOptionGroup',
      'DatePicker',
      'Dropdown',
      'FileUpload',
      'FormField',
      'FormGenerator',
      'RangeSlider',
      'Search',
      'Switch',
      'SwitchPanel',
    ],
  ],
  Iconography: [
    'A comprehensive library of free fonts provided bu Font Awesome.',
    ['Icons', 'Flag'],
  ],
  Informational: [
    'Informational components are used to convey helpful information to the user.',
    [
      'Alert',
      'Badge',
      'Cart',
      'Hint',
      'Label',
      'ProgressBar',
      'Price',
      'Rating',
      'Statistic',
      'Spinner',
      'Tooltip',
    ],
  ],
  Landmarks: ['Landmarks are major sections on a page', ['Header', 'Footer']],
  Layout: [
    'Layout components are used to provide formatting for page content.',
    ['Media'],
  ],
  Navigation: [
    'Navigation components are used to provide a means to navigate throught an app or website, or provide a means to advance back and forth between content.',
    ['Breadcrumb', 'Link', 'Pagination', 'Stepper'],
  ],
  'Payment Wallet': [
    "Here you'll find components that can be used to compose a payment wallet UI for your application.",
    ['Wallet', 'WalletItem'],
  ],
  Providers: [
    'Providers are HOCs (Higher Order Components) that wrap another component, providing it with access to additional functionality.',
    ['WithToastProvider'],
  ],
  Experimental: [
    'Experimental components can be used, but are not at a stable point yet, and are subject to change.',
    ['CreditCardField'],
  ],
  'Sass Utilities': [
    'CSS utilities include classes to add.',
    ['Colors', 'Spacing', 'Typography', 'Utility Classes'],
  ],
  Recipes: [
    'These recipes can be used to kickstart your project and provide best-practices and helpful suggestions.',
    ['Form Validation', 'Grid', 'Pop Confirm'],
  ],
};
