export default {
  Containers: [
    'Card',
    'ChatWindow',
    'Collapse',
    'Drawer',
    'Jumbotron',
    'Modal',
    'Overlay',
  ],
  Content: [
    'Accordion',
    'AccordionItem',
    'Avatar',
    'Badge',
    'Quotation',
    'Comment',
    'Post',
    'TabPanel',
    'Tabs',
    'Tab',
    'Tag',
    'Truncate',
  ],
  'Data Display': ['List', 'ListItem', 'Table'],
  DOM: ['Portal'],
  'Form controls': [
    'AutoComplete',
    'Button',
    'ButtonGroup',
    'CheckOption',
    'DatePicker',
    'Dropdown',
    'FileUpload',
    'FormField',
    'FormGenerator',
    'RangeSlider',
    'Search',
    'Switch',
    'SwitchPanel',
  ],
  Iconography: ['Icons', 'Flag'],
  Informational: [
    'Alert',
    'Badge',
    'Cart',
    'CartItem',
    'Hint',
    'Label',
    'ProgressBar',
    'Price',
    'Rating',
    'Statistic',
    'Spinner',
    'Tooltip',
  ],
  Landmarks: ['Header', 'Footer'],
  Layout: ['Media'],
  Navigation: ['Breadcrumb', 'Link', 'Pagination', 'Step', 'Stepper'],
  'Payment Wallet': ['Wallet', 'WalletItem'],
  Providers: ['WithToastProvider'],
  Experiemental: ['CreditCardField'],
};
